#!/bin/bash

# Database connection details
DB_NAME="postgres"
DB_USER="postgres.ajherylcstmvumfetlul"
DB_HOST="aws-0-us-east-1.pooler.supabase.com" # e.g., localhost
DB_PORT="6543"                                # e.g., 5432
SCHEMA_NAME="casino"                          # Change if your schema is different

# Directory to save the CSV files
CSV_DIR="./casino_schema_csv"
mkdir -p "$CSV_DIR"

# List of tables in the casino schema
TABLES=(
    "apikeys"
    "app_usage"
    "app_versions"
    "app_versions_meta"
    "apps"
    "bandwidth_usage"
    "channel_devices"
    "channels"
    "daily_bandwidth"
    "daily_mau"
    "daily_storage"
    "daily_version"
    "deleted_account"
    "device_usage"
    "devices"
    "devices_override"
    "games"
    "global_stats"
    "job_queue"
    "notifications"
    "org_users"
    "orgs"
    "plans"
    "stats"
    "storage_usage"
    "stripe_info"
    "users"
    "version_meta"
    "version_usage"
    "w_categories"
    "w_credits"
    "w_failed_jobs"
    "w_faqs"
    "w_fish_bank"
    "w_game_bank"
    "w_game_categories"
    "w_game_log"
    "w_games"
    "w_happyhours"
    "w_info"
    "w_info_shop"
    "w_invites"
    "w_jobs"
    "w_jpg"
    "w_messages"
    "w_notifications"
    "w_open_shift"
    "w_open_shift_temp"
    "w_password_resets"
    "w_pay_tickets"
    "w_payment_settings"
    "w_payments"
    "w_permission_role"
    "w_permission_user"
    "w_permissions"
    "w_pincodes"
    "w_progress"
    "w_progress_users"
    "w_quick_shops"
    "w_rewards"
    "w_role_user"
    "w_roles"
    "w_rules"
    "w_securities"
    "w_sessions"
    "w_settings"
    "w_shop_categories"
    "w_shops"
    "w_shops_countries"
    "w_shops_devices"
    "w_shops_os"
    "w_shops_user"
    "w_sms"
    "w_sms_bonus_items"
    "w_sms_bonuses"
    "w_sms_mailing_messages"
    "w_sms_mailings"
    "w_stat_game"
    "w_statistics"
    "w_statistics_add"
    "w_subsessions"
    "w_tasks"
    "w_tickets"
    "w_tickets_answers"
    "w_tournament_bots"
    "w_tournament_categories"
    "w_tournament_games"
    "w_tournament_prizes"
    "w_tournament_stats"
    "w_tournaments"
    "w_user_activity"
    "w_users"
    "w_welcomebonuses"
    "w_wheelfortune"
    "w_withdraw_funds"
    "workers"
)
export PGPASSWORD=ajherylcstmvumfetlul
# Loop through each table and export to CSV
for TABLE in "${TABLES[@]}"; do
    echo "Exporting table: $TABLE to CSV"
    psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -c "\COPY $SCHEMA_NAME.$TABLE TO '$CSV_DIR/$TABLE.csv' WITH (FORMAT CSV, HEADER);"
done

echo "All tables have been exported to CSV in $CSV_DIR."
